ibexa_design_integration.api.pager:
    path: /api/pager/v1/{type}
    controller: ErdnaxelaWeb\IbexaDesignIntegrationBundle\Controller\Api\PagerController::getPager
    methods: [GET]

ibexa_design_integration.api.pager.options:
    path: /api/pager/v1/{type}
    controller: ErdnaxelaWeb\IbexaDesignIntegrationBundle\Controller\Api\PagerController::optionsPager
    methods: [OPTIONS]
