services:
    ErdnaxelaWeb\IbexaDesignIntegration\Component\ComponentFinder:
        decorates: ErdnaxelaWeb\StaticFakeDesign\Component\ComponentFinder
        parent: ErdnaxelaWeb\StaticFakeDesign\Component\ComponentFinder
        arguments:
            $designList: '%ibexa.design.list%'
            $templatePathsMap: '%ibexa.design.templates.path_map%'
        calls:
            - ['setConfigResolver', ['@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface']]

    ErdnaxelaWeb\IbexaDesignIntegration\Component\ComponentBuilder:
        decorates: ErdnaxelaWeb\StaticFakeDesign\Component\ComponentBuilder
        parent: ErdnaxelaWeb\StaticFakeDesign\Component\ComponentBuilder
