services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\ContentTransformer:
        arguments:
            $breadcrumbGenerator: '@ErdnaxelaWeb\IbexaDesignIntegration\Helper\BreadcrumbGenerator'
            $contentConfigurationManager: '@ErdnaxelaWeb\IbexaDesignIntegration\Configuration\ContentConfigurationManager'
            $fieldValueTransformers: '@ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValueTransformer'
            $contentService: '@Ibexa\Contracts\Core\Repository\ContentService'
            $locationService: '@Ibexa\Contracts\Core\Repository\LocationService'
            $responseTagger: '@Ibexa\HttpCache\Handler\TagHandler'

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValueTransformer:
        arguments:
            $transformers: !tagged_iterator { tag: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', index_by: 'type' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.ezboolean:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        arguments:
            $propertyName: 'bool'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezboolean' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.ezdate:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        arguments:
            $propertyName: 'date'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezdate' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.ezemail:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        arguments:
            $propertyName: 'email'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezemail' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.ezstring:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        arguments:
            $propertyName: 'text'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezstring' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.eztime:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        arguments:
            $propertyName: 'time'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'eztime' }

    erdnaxelaweb.ibexa_design_integration.transformer.field_value.generic:
        class: ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\GenericFieldValueTransformer
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezdatetime' }
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezfloat' }
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezinteger' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\FileFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezbinaryfile' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\TextFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'eztext' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\LocationFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezgmaplocation' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\RichtextFieldValueTransformer:
        lazy: true
        arguments:
            $richTextOutputConverter: '@ibexa.richtext.converter.output.xhtml5'
            $fieldHelper: '@Ibexa\Core\Helper\FieldHelper'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezrichtext' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\SelectionFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezselection' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\MatrixFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezmatrix' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\ImageFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezimage' }
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezimageasset' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\ContentFieldValueTransformer:
        lazy: true
        arguments:
            $contentTransformer: '@ErdnaxelaWeb\IbexaDesignIntegration\Transformer\ContentTransformer'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezobjectrelation' }
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezobjectrelationlist' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\UrlFieldValueTransformer:
        lazy: true
        arguments:
            $factory: '@knp_menu.factory'
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ezurl' }

    # form
    # taxo
    # block
